import os
import json
from pathlib import Path
from dotenv import load_dotenv

# Load env to get Groq API key
load_dotenv(Path(__file__).resolve().parent.parent / ".env")

try:
    from groq import Groq
except ImportError:
    print("Please install groq: pip install groq")
    exit(1)

EVALUATOR_PROMPT = """System: You are an expert Quality Assurance Evaluator for an e-commerce networking hardware chatbot (selling routers, server racks, cable stairs). 

Your objective is to grade the Chatbot's response based strictly on the user's query and the ground truth data provided by the system's tools (API/Database or RAG knowledge base).

You will be provided with three inputs:
1. [User Query]: The customer's message.
2. [System Data]: The exact data returned by the system's database or RAG pipeline (e.g., stock levels, prices, tax rates, or product manuals).
3. [Chatbot Response]: The final message generated by the chatbot.

Evaluate the Chatbot Response against the following four criteria. Grade each on a binary scale (1 for Pass, 0 for Fail).

### Evaluation Criteria:

1. FAITHFULNESS & ACCURACY (Did it stick to the facts?)
- Pass (1): The chatbot ONLY used information present in the [System Data]. It accurately reflected stock availability, arrival dates, and product specs without inventing anything.
- Fail (0): The chatbot hallucinated a feature, promised a delivery date not in the data, or quoted a price not provided.

2. MATHEMATICAL CORRECTNESS (Did it calculate costs properly?)
- Pass (1): If the user asked for a total, the chatbot correctly added the base price, shipping, and calculated the correct tax based on the [System Data]. 
- Fail (0): The math is wrong, or it failed to mention that taxes are excluded if location data was missing. (If no math was required, default to 1).

3. ROUTING & TOOL USE (Did it rely on the right context?)
- Pass (1): The chatbot addressed the query using the appropriate data source (e.g., answering a spec question using a manual, or answering a price question using inventory data).
- Fail (0): The chatbot ignored the provided [System Data] or stated it couldn't answer when the data was clearly provided.

4. BUSINESS LOGIC & TONE (Did it follow sales protocols?)
- Pass (1): The response is professional. If an item is out of stock, it suggested an alternative from the data. If an active offer exists in the data, it mentioned it.
- Fail (0): The bot was rude, broke character, failed to suggest an alternative for a zero-stock item, or ignored an active discount code.

### Output Format:
You must output ONLY a valid JSON object. Do not include markdown formatting, explanations outside the JSON, or conversational filler. 

{{
  "faithfulness_score": <0 or 1>,
  "math_score": <0 or 1>,
  "routing_score": <0 or 1>,
  "business_logic_score": <0 or 1>,
  "reasoning": "<Provide a concise, 1-2 sentence explanation of why any score was a 0. If all scores are 1, output 'Perfect response.'>"
}}

---
INPUT DATA:

[User Query]: {user_input}

[System Data]: {retrieved_context}

[Chatbot Response]: {bot_output}"""


def evaluate_interaction(user_input: str, retrieved_context: str, bot_output: str) -> dict:
    """Uses an LLM (Groq) to evaluate a chatbot interaction based on the strict rubric."""
    client = Groq(api_key=os.getenv("GROQ_API_KEY"))
    prompt = EVALUATOR_PROMPT.format(
        user_input=user_input,
        retrieved_context=retrieved_context,
        bot_output=bot_output
    )
    
    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",  # Fast, cheap model perfect for JSON evaluation
        messages=[{"role": "user", "content": prompt}],
        temperature=0.0,
        response_format={"type": "json_object"}
    )
    
    raw = response.choices[0].message.content.strip()
    print("RAW OUTPUT:", repr(raw))
    if raw.startswith("```json"):
        raw = raw[7:]
    elif raw.startswith("```"):
        raw = raw[3:]
    if raw.endswith("```"):
        raw = raw[:-3]
    return json.loads(raw.strip())


if __name__ == "__main__":
    # A quick dummy test if run directly
    print("Running a sample evaluation...")
    
    sample_query = "Do you have the FortiGate 40F in stock and what's the total cost with 18% tax?"
    sample_context = "[Product] FortiGate 40F | Price: 80,000 INR | Stock: 10 units"
    sample_bot_response = "Yes, we have 10 units of the FortiGate 40F in stock! The base price is 80,000 INR. With 18% tax, the total cost would be 94,400 INR."
    
    try:
        result = evaluate_interaction(sample_query, sample_context, sample_bot_response)
        print("\nEvaluation Results:")
        print(json.dumps(result, indent=2))
    except Exception as e:
        print(f"Error evaluating: {e}")
